### ISSUE TITLE
Fails on this input

### ISSUE THREAD

**Issue by photopea** [101arrowz/fzstd#9]
The library fails at this input. Is it a bug in a library or in the input
[data.txt](https://github.com/101arrowz/fzstd/files/9040311/data.txt)
?

**Comment by 101arrowz** [comment]
That file yields a 4.2 GB output PDF. Obviously this will fail to decompress in memory. I tried to decompress with the streaming decompressor and it yielded the same output as `zstd -d` (and it was actually faster, surprisingly - probably due to I/O bandwidth limitations). What code did you use to decompress?

**Comment by photopea** [comment]
What about this array? Is it a valid zstd stream? I can not decode it with any decoder.

[data.txt](https://github.com/101arrowz/fzstd/files/10002228/data.txt)

**Comment by 101arrowz** [comment]
The decompressed size of that file is 2.66GB, which is still too large to decompress in memory. I think JavaScript engines in general support up to 2^31 bytes (2GiB or about 2.14GB), though Firefox should support more.
